import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import LayoutClient from "@/components/common/LayoutClient";

const inter = Inter({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[#F6F7F8] min-h-screen w-full`}
      >
        <Toaster position="bottom-right" />
        <LayoutClient>
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
